/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.univalle.vista;

import co.edu.univalle.controlador.CtrIniciarSesion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JOptionPane;

/**
 *
 * @author JHOJAN L
 */
public class IniciarSesion extends javax.swing.JFrame {
    
    FondoPanel fondo = new FondoPanel();

   class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/white.jpg")).getImage();
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
    
    
    public IniciarSesion()  {

        this.setContentPane(fondo);
        
        initLookAndFeel();
        initComponents();
        CtrIniciarSesion ctrl = new CtrIniciarSesion(this);
        jPanel.setFocusable(true);
        jPanel.addKeyListener(ctrl);
        jbIniciarSesion.addActionListener(ctrl);
        jbRegistro.addActionListener(ctrl);
        jlOlvidarPassword.addMouseListener(ctrl);

    }

    /**
     * ma This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new FondoPanel();
        jlUsuarioCodigo1 = new javax.swing.JLabel();
        jlOlvidarPassword = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbIniciarSesion = new javax.swing.JButton();
        jbRegistro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jlNombreAplicacion = new javax.swing.JLabel();
        jtPassword = new javax.swing.JPasswordField();
        jtCodigo = new javax.swing.JFormattedTextField();
        jcTipoUsuario = new javax.swing.JComboBox<>();
        jlTipoUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIAR SESION");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jlUsuarioCodigo1.setText("CODIGO:");

        jlOlvidarPassword.setText("Olvide mi contraseña");

        jLabel5.setText("CONTRASEÑA:");

        jbIniciarSesion.setText("Iniciar Sesion");

        jbRegistro.setText("Crear Cuenta");

        jlNombreAplicacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlNombreAplicacion.setText("OLIMPIADAS DEL SOFTWARE");
        jlNombreAplicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jtCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jcTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Profesor", "Estudiante" }));

        jlTipoUsuario.setText("TIPO DE USUARIO:");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jbRegistro)))
                .addGap(202, 202, 202))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jlNombreAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jbIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlTipoUsuario)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlOlvidarPassword)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlUsuarioCodigo1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcTipoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jlNombreAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jlTipoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jlUsuarioCodigo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlOlvidarPassword)
                .addGap(18, 18, 18)
                .addComponent(jbIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbIniciarSesion;
    private javax.swing.JButton jbRegistro;
    private javax.swing.JComboBox<String> jcTipoUsuario;
    private javax.swing.JLabel jlNombreAplicacion;
    private javax.swing.JLabel jlOlvidarPassword;
    private javax.swing.JLabel jlTipoUsuario;
    private javax.swing.JLabel jlUsuarioCodigo1;
    private javax.swing.JFormattedTextField jtCodigo;
    private javax.swing.JPasswordField jtPassword;
    // End of variables declaration//GEN-END:variables

    private void initLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JPanel getjPanel() {
        return jPanel;
    }

    public void setjPanel(JPanel jPanel) {
        this.jPanel = jPanel;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JButton getJbIniciarSesion() {
        return jbIniciarSesion;
    }

    public void setJbIniciarSesion(JButton jbIniciarSesion) {
        this.jbIniciarSesion = jbIniciarSesion;
    }

    public JButton getJbRegistro() {
        return jbRegistro;
    }

    public void setJbRegistro(JButton jbRegistro) {
        this.jbRegistro = jbRegistro;
    }

    public JComboBox<String> getJcTipoUsuario() {
        return jcTipoUsuario;
    }

    public void setJcTipoUsuario(JComboBox<String> jcTipoUsuario) {
        this.jcTipoUsuario = jcTipoUsuario;
    }

    public JLabel getJlNombreAplicacion() {
        return jlNombreAplicacion;
    }

    public void setJlNombreAplicacion(JLabel jlNombreAplicacion) {
        this.jlNombreAplicacion = jlNombreAplicacion;
    }

    public JLabel getJlOlvidarPassword() {
        return jlOlvidarPassword;
    }

    public void setJlOlvidarPassword(JLabel jlOlvidarPassword) {
        this.jlOlvidarPassword = jlOlvidarPassword;
    }

    public JLabel getJlTipoUsuario() {
        return jlTipoUsuario;
    }

    public void setJlTipoUsuario(JLabel jlTipoUsuario) {
        this.jlTipoUsuario = jlTipoUsuario;
    }

    public JLabel getJlUsuarioCodigo1() {
        return jlUsuarioCodigo1;
    }

    public void setJlUsuarioCodigo1(JLabel jlUsuarioCodigo1) {
        this.jlUsuarioCodigo1 = jlUsuarioCodigo1;
    }

    public JFormattedTextField getJtCodigo() {
        return jtCodigo;
    }

    public void setJtCodigo(JFormattedTextField jtCodigo) {
        this.jtCodigo = jtCodigo;
    }

    public JPasswordField getJtPassword() {
        return jtPassword;
    }

    public void setJtPassword(JPasswordField jtPassword) {
        this.jtPassword = jtPassword;
    }

}
