/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.univalle.vista;

import co.edu.univalle.controlador.CtrInterfazEstudiante;
import co.edu.univalle.modelo.Estudiante;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author JHOJAN L
 */
public class InterfazEstudiante extends javax.swing.JFrame {

    private Estudiante estudianteLog;
    private ImageIcon icon;
    private ImageIcon imagen;

    /**
     * Creates new form InterfazEstudiante
     */
    public InterfazEstudiante(Estudiante estudianteLog) {
        this.setContentPane(fondo);
        this.estudianteLog = estudianteLog;
        initComponents();

        jlNombre.setText(this.estudianteLog.getNombre());//establecemos nombre y el avatar
        asignarImagen(jlAvatar, this.estudianteLog.getCodigoAvatar().getImg());

        CtrInterfazEstudiante ctrl = new CtrInterfazEstudiante(this, estudianteLog);
        jlSalir.addMouseListener(ctrl);
        jlConfig.addMouseListener(ctrl);
        jlJuego.addMouseListener(ctrl);
        jlModulos.addMouseListener(ctrl);
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jlAvatar = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlSalir = new javax.swing.JLabel();
        jlConfig = new javax.swing.JLabel();
        jlModulos = new javax.swing.JLabel();
        jlJuego = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNombre.setText("nombre");

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jlSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa.png"))); // NOI18N
        jlSalir.setToolTipText("Salir");
        jlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/config.png"))); // NOI18N
        jlConfig.setToolTipText("Configuracion");
        jlConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlConfig.setPreferredSize(new java.awt.Dimension(21, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlConfig, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlModulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modulos.png"))); // NOI18N
        jlModulos.setToolTipText("Modulos");
        jlModulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/juegos.png"))); // NOI18N
        jlJuego.setToolTipText("Juego");
        jlJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jlModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(jlJuego)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlModulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void asignarImagen(JLabel label, String ruta) {
        this.imagen = new ImageIcon(ruta);//establecemos la ruta
        this.icon = new ImageIcon(this.imagen.getImage().getScaledInstance(
                label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));

        label.setIcon(this.icon);
        this.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlAvatar;
    private javax.swing.JLabel jlConfig;
    private javax.swing.JLabel jlJuego;
    private javax.swing.JLabel jlModulos;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlSalir;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JLabel getJlAvatar() {
        return jlAvatar;
    }

    public void setJlAvatar(JLabel jlAvatar) {
        this.jlAvatar = jlAvatar;
    }

    public JLabel getJlConfig() {
        return jlConfig;
    }

    public void setJlConfig(JLabel jlConfig) {
        this.jlConfig = jlConfig;
    }

    public JLabel getJlJuego() {
        return jlJuego;
    }

    public void setJlJuego(JLabel jlJuego) {
        this.jlJuego = jlJuego;
    }


    public JLabel getJlModulos() {
        return jlModulos;
    }

    public void setJlModulos(JLabel jlModulos) {
        this.jlModulos = jlModulos;
    }

    public JLabel getJlNombre() {
        return jlNombre;
    }

    public void setJlNombre(JLabel jlNombre) {
        this.jlNombre = jlNombre;
    }

    

    public JLabel getJlSalir() {
        return jlSalir;
    }

    public void setJlSalir(JLabel jlSalir) {
        this.jlSalir = jlSalir;
    }

FondoPanel fondo = new FondoPanel();

   class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/white.jpg")).getImage();
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }

}
