/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.univalle.vista;

import co.edu.univalle.controlador.CtrInterfazAdministrador;
import co.edu.univalle.modelo.Administrador;
import static co.edu.univalle.vista.GestionAdministrador.ventanaAdministradorActiva;
import static co.edu.univalle.vista.GestionEstudiante.ventanaEstudianteActiva;
import static co.edu.univalle.vista.GestionProfesor.ventanaProfesorActiva;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author JHOJAN L
 */
public class InterfazAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAdministrador
     */
    
    private Administrador adminLog;
    private ImageIcon icon;
    private ImageIcon imagen;
    
    public InterfazAdministrador(Administrador adminLog) {
        initComponents();
        ventanaAdministradorActiva=null;//cada que se cargue el constructor el chequeo de las ventanas activas seran nulas para poder abrirlas
        ventanaProfesorActiva=null;
        ventanaEstudianteActiva=null;
        
        this.adminLog = adminLog;
        jlUsuario.setText(adminLog.getUsuario());
        asignarImagen(jlAvatar, adminLog.getCodigoAvatar().getImg());
        
        CtrInterfazAdministrador ctrl = new CtrInterfazAdministrador(this,this.adminLog);
        jbGestionAdmin.addActionListener(ctrl);
        jbGestionProfesor.addActionListener(ctrl);
        jbGestionEstudiante.addActionListener(ctrl);
        jlSalir.addMouseListener(ctrl);
        jlConfig.addMouseListener(ctrl);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlAvatar = new javax.swing.JLabel();
        jlConfig = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jbGestionAdmin = new javax.swing.JButton();
        jlGestionInformacion = new javax.swing.JLabel();
        jbGestionProfesor = new javax.swing.JButton();
        jbGestionEstudiante = new javax.swing.JButton();
        jlSalir = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/config.png"))); // NOI18N
        jlConfig.setToolTipText("Configuracion");
        jlConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlUsuario.setText("nombre usuario");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 204), null));

        jbGestionAdmin.setText("Administrador");

        jlGestionInformacion.setText("Gestionar informacion de:");

        jbGestionProfesor.setText("Profesor");

        jbGestionEstudiante.setText("Estudiante");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbGestionProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbGestionEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jbGestionAdmin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlGestionInformacion)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlGestionInformacion)
                .addGap(54, 54, 54)
                .addComponent(jbGestionAdmin)
                .addGap(51, 51, 51)
                .addComponent(jbGestionProfesor)
                .addGap(45, 45, 45)
                .addComponent(jbGestionEstudiante)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jlSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa.png"))); // NOI18N
        jlSalir.setToolTipText("Salir");
        jlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlConfig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlSalir)
                .addGap(127, 127, 127))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jSeparator1)
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jlUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlConfig)
                    .addComponent(jlSalir))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

     public void asignarImagen(JLabel label, String ruta){
        this.imagen = new ImageIcon(ruta);//establecemos la ruta
        this.icon = new ImageIcon(this.imagen.getImage().getScaledInstance(
                label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        
        label.setIcon(this.icon);
        this.repaint();
    
    }
    public Administrador getAdminLog() {
        return adminLog;
    }

    public void setAdminLog(Administrador adminLog) {
        this.adminLog = adminLog;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JButton getJbGestionAdmin() {
        return jbGestionAdmin;
    }

    public void setJbGestionAdmin(JButton jbGestionAdmin) {
        this.jbGestionAdmin = jbGestionAdmin;
    }

    public JButton getJbGestionEstudiante() {
        return jbGestionEstudiante;
    }

    public void setJbGestionEstudiante(JButton jbGestionEstudiante) {
        this.jbGestionEstudiante = jbGestionEstudiante;
    }

    public JButton getJbGestionProfesor() {
        return jbGestionProfesor;
    }

    public void setJbGestionProfesor(JButton jbGestionProfesor) {
        this.jbGestionProfesor = jbGestionProfesor;
    }

    public JLabel getJlAvatar() {
        return jlAvatar;
    }

    public void setJlAvatar(JLabel jlAvatar) {
        this.jlAvatar = jlAvatar;
    }

    public JLabel getJlConfig() {
        return jlConfig;
    }

    public void setJlConfig(JLabel jlConfig) {
        this.jlConfig = jlConfig;
    }

    public JLabel getJlGestionInformacion() {
        return jlGestionInformacion;
    }

    public void setJlGestionInformacion(JLabel jlGestionInformacion) {
        this.jlGestionInformacion = jlGestionInformacion;
    }

    public JLabel getJlUsuario() {
        return jlUsuario;
    }

    /**
     * @param args the command line arguments
     */
    public void setJlUsuario(JLabel jlUsuario) {
        this.jlUsuario = jlUsuario;
    }

    public JLabel getJlSalir() {
        return jlSalir;
    }

    public void setJlSalir(JLabel jlSalir) {
        this.jlSalir = jlSalir;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbGestionAdmin;
    private javax.swing.JButton jbGestionEstudiante;
    private javax.swing.JButton jbGestionProfesor;
    private javax.swing.JLabel jlAvatar;
    private javax.swing.JLabel jlConfig;
    private javax.swing.JLabel jlGestionInformacion;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JLabel jlUsuario;
    // End of variables declaration//GEN-END:variables
}
