/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.univalle.vista;

import co.edu.univalle.controlador.CtrRecuperarCuenta;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author JHOJAN L
 */
public class RecuperarCuenta extends javax.swing.JFrame {

    /**
     * Creates new form OlvidarPassword
     */
    public RecuperarCuenta() {
        initComponents();
        CtrRecuperarCuenta ctrl = new CtrRecuperarCuenta(this);
        jlAtras.addMouseListener(ctrl);
        jbCambiarPassword.addActionListener(ctrl);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcTipoUsuario = new javax.swing.JComboBox<>();
        jlTipoUsuario = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jbCambiarPassword = new javax.swing.JButton();
        jtPassNew = new javax.swing.JTextField();
        jlPassNew = new javax.swing.JLabel();
        jlAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTRASEÑA NUEVA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jcTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Profesor", "Estudiante" }));

        jlTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTipoUsuario.setText("TIPO DE USUARIO:");

        jlCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCodigo.setText("CODIGO:");

        jtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbCambiarPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCambiarPassword.setText("OK");

        jtPassNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlPassNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlPassNew.setText("CONTRASEÑA NUEVA:");

        jlAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/retorno.png"))); // NOI18N
        jlAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlTipoUsuario)
                            .addComponent(jlPassNew)
                            .addComponent(jlCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCodigo)
                            .addComponent(jcTipoUsuario, 0, 118, Short.MAX_VALUE)
                            .addComponent(jtPassNew))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbCambiarPassword)
                        .addGap(221, 221, 221))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipoUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPassNew)
                    .addComponent(jtPassNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jbCambiarPassword)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCambiarPassword;
    private javax.swing.JComboBox<String> jcTipoUsuario;
    private javax.swing.JLabel jlAtras;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlPassNew;
    private javax.swing.JLabel jlTipoUsuario;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtPassNew;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JButton getJbCambiarPassword() {
        return jbCambiarPassword;
    }

    public void setJbCambiarPassword(JButton jbCambiarPassword) {
        this.jbCambiarPassword = jbCambiarPassword;
    }

    public JComboBox<String> getJcTipoUsuario() {
        return jcTipoUsuario;
    }

    public void setJcTipoUsuario(JComboBox<String> jcTipoUsuario) {
        this.jcTipoUsuario = jcTipoUsuario;
    }

    public JLabel getJlCodigo() {
        return jlCodigo;
    }

    public void setJlCodigo(JLabel jlCodigo) {
        this.jlCodigo = jlCodigo;
    }

    public JLabel getJlCodigo1() {
        return jlPassNew;
    }

    public void setJlCodigo1(JLabel jlCodigo1) {
        this.jlPassNew = jlCodigo1;
    }

    public JLabel getJlTipoUsuario() {
        return jlTipoUsuario;
    }

    public void setJlTipoUsuario(JLabel jlTipoUsuario) {
        this.jlTipoUsuario = jlTipoUsuario;
    }

    public JTextField getJtCodigo() {
        return jtCodigo;
    }

    public void setJtCodigo(JTextField jtCodigo) {
        this.jtCodigo = jtCodigo;
    }

    public JTextField getJtPassNew() {
        return jtPassNew;
    }

    public void setJtPassNew(JTextField jtPassNew) {
        this.jtPassNew = jtPassNew;
    }

    public JLabel getJlAtras() {
        return jlAtras;
    }

    public void setJlAtras(JLabel jlAtras) {
        this.jlAtras = jlAtras;
    }

    

}
