/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.univalle.vista;

import co.edu.univalle.controlador.*;
import co.edu.univalle.modelo.Estudiante;
import co.edu.univalle.modelo.Modulo;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author JHOJAN L
 */
public class VistaModulo3 extends javax.swing.JFrame {

    private Modulo modulo;
    private Estudiante estudiante;

    /**
     * Creates new form VistaModulo1
     */
    public VistaModulo3(Modulo modulo, Estudiante estudiante) {
        initComponents();
        
        this.modulo = modulo;
        this.estudiante = estudiante;
        CtrVistaModulo3 ctrl = new CtrVistaModulo3(this, this.modulo);
        
        jlNombreModulo.setText(modulo.getNombre());
        jbSubModulo1.addActionListener(ctrl);
        jbSubModulo2.addActionListener(ctrl);
        jbSubModulo3.addActionListener(ctrl);
        jbSubModulo4.addActionListener(ctrl);
        jbSubModulo5.addActionListener(ctrl);
        jlAtras.addMouseListener(ctrl);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbSubModulo1 = new javax.swing.JButton();
        jlNombreModulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane = new javax.swing.JEditorPane();
        jbSubModulo2 = new javax.swing.JButton();
        jbSubModulo3 = new javax.swing.JButton();
        jlAtras = new javax.swing.JLabel();
        jbSubModulo4 = new javax.swing.JButton();
        jbSubModulo5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 450));

        jbSubModulo1.setText("¿Que es un lenguaje de programacion?");

        jlNombreModulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNombreModulo.setText("Lenguajes de programacion");

        jEditorPane.setEditable(false);
        jEditorPane.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(jEditorPane);

        jbSubModulo2.setText("Lenguajes mas utilizados");

        jbSubModulo3.setText("Java");

        jlAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/retorno.png"))); // NOI18N
        jlAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbSubModulo4.setText("PHP");

        jbSubModulo5.setText("Phyton");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlAtras))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addComponent(jbSubModulo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombreModulo)
                            .addComponent(jbSubModulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSubModulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSubModulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSubModulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jlNombreModulo)
                .addGap(42, 42, 42)
                .addComponent(jbSubModulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSubModulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSubModulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSubModulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSubModulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlAtras)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbSubModulo1;
    private javax.swing.JButton jbSubModulo2;
    private javax.swing.JButton jbSubModulo3;
    private javax.swing.JButton jbSubModulo4;
    private javax.swing.JButton jbSubModulo5;
    private javax.swing.JLabel jlAtras;
    private javax.swing.JLabel jlNombreModulo;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JEditorPane getjEditorPane() {
        return jEditorPane;
    }

    public void setjEditorPane(JEditorPane jEditorPane) {
        this.jEditorPane = jEditorPane;
    }

    public JButton getJbSubModulo1() {
        return jbSubModulo1;
    }

    public void setJbSubModulo1(JButton jbSubModulo1) {
        this.jbSubModulo1 = jbSubModulo1;
    }

    public JLabel getJlNombreModulo() {
        return jlNombreModulo;
    }

    public void setJlNombreModulo(JLabel jlNombreModulo) {
        this.jlNombreModulo = jlNombreModulo;
    }

    public JButton getJbSubModulo2() {
        return jbSubModulo2;
    }

    public void setJbSubModulo2(JButton jbSubModulo2) {
        this.jbSubModulo2 = jbSubModulo2;
    }

    public JButton getJbSubModulo3() {
        return jbSubModulo3;
    }

    public void setJbSubModulo3(JButton jbSubModulo3) {
        this.jbSubModulo3 = jbSubModulo3;
    }

    public JLabel getJlAtras() {
        return jlAtras;
    }

    public void setJlAtras(JLabel jlAtras) {
        this.jlAtras = jlAtras;
    }

    public Estudiante getEstudiante() {
        return estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public JButton getJbSubModulo4() {
        return jbSubModulo4;
    }

    public void setJbSubModulo4(JButton jbSubModulo4) {
        this.jbSubModulo4 = jbSubModulo4;
    }

    public JButton getJbSubModulo5() {
        return jbSubModulo5;
    }

    public void setJbSubModulo5(JButton jbSubModulo5) {
        this.jbSubModulo5 = jbSubModulo5;
    }
    
    
    

}
